### ISSUE TITLE
Not Working, it already got patched IG

### ISSUE THREAD

**Issue by NatsumeAoii** [DoingFedTime/LinkedInAuto-ConnectBot#1]
got error

VM838:58 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'report-sample' 'sha256-6gLjSWp3GRKZCUFvRX5aGHtECD1wVRgJOJp7r0ZQjV0=' static.licdn.com static-exp1.licdn.com static-exp2.licdn.com static-exp3.licdn.com www.linkedin.com/sc/ www.linkedin.com/scds/ www.linkedin.com/voyager/abp-detection.js piwik.corp.linkedin.com/piwik/piwik.js platform.linkedin.com/js/analytics.js platform-akam.linkedin.com/js/analytics.js platform-ecst.linkedin.com/js/analytics.js platform-azur.linkedin.com/js/analytics.js platform.linkedin.com/litms/utag/ platform-akam.linkedin.com/litms/utag/ platform-ecst.linkedin.com/litms/utag/ platform-azur.linkedin.com/litms/utag/ platform.linkedin.com/litms/vendor/ platform-akam.linkedin.com/litms/vendor/ platform-ecst.linkedin.com/litms/vendor/ platform-azur.linkedin.com/litms/vendor/ www.googletagmanager.com/gtag/js snap.licdn.com/li.lms-analytics/ www.googleadservices.com/pagead/ www.google.com/pagead/ googleads.g.doubleclick.net/pagead/ adservice.google.com/pagead/ merchantpool1.linkedin.com/mdt.js". Either the 'unsafe-inline' keyword, a hash ('sha256-5+YTmTcBwCYdJ8Jetbr6kyjGp0Ry/H7ptpoun6CrSwQ='), or a nonce ('nonce-...') is required to enable inline execution.

injectViaScriptTag @ VM838:58
injectFunc @ VM838:72
(anonymous) @ VM838:80Understand this errorAI
VM925:22 Refused to create a TrustedTypePolicy named 'AGPolicy' because it violates the following Content Security Policy directive: "trusted-types 'allow-duplicates' default jSecure highcharts dompurify".
injectFunc @ VM925:22
(anonymous) @ VM925:80Understand this errorAI
VM925:22 
        
       Uncaught TypeError: Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy "AGPolicy" disallowed.
    at injectFunc (<anonymous>:22:39)
    at <anonymous>:80:11

**Comment by DoingFedTime** [comment]
I just tried it in brave and had no issues.
What browser are you using?

**Comment by NatsumeAoii** [comment]
I am using chrome, win 10

**Comment by DoingFedTime** [comment]
Thanks for reporting this issue! Interestingly, the script works in my setup (and also Chrome) but throws errors for you. Based on the error you shared, the problem seems tied to LinkedIn’s Content Security Policy (CSP) or Trusted Types configuration. That said, I had zero issues when running it on my throwaway account (besides the 'to many' error you see in the video, which ahs nothing to do with the errors you were getting). From my limited understanding, these can vary depending on factors like your active browser extensions or even localized DOM changes.  

Here’s a more detailed breakdown of what might be happening and how to troubleshoot:  

### Possible Causes and Fixes  

1. **Content Security Policy (CSP) Restrictions**:  
   LinkedIn enforces strict CSP rules to block inline scripts unless specific conditions (e.g., `sha256` hashes or `nonce` attributes) are met. These policies might differ based on your LinkedIn environment.  
   - **Test**: Open DevTools (F12) > Network tab > Reload the page. Look for the `Content-Security-Policy` header in LinkedIn's responses. If CSP rules are blocking inline scripts, you'll see entries like `script-src` or `trusted-types`.  
   - **Solution**: Instead of running the script directly in the console, you can inject it as an external script dynamically:
     ```javascript
     const script = document.createElement('script');
     script.src = 'https://your-server.com/linkedInBot.js'; // Host your script externally
     document.body.appendChild(script);
     ```

2. **Trusted Types Blocking DOM Manipulations**:  
   LinkedIn uses Trusted Types to prevent DOM-based vulnerabilities. If your script’s DOM manipulations (e.g., `querySelector` or `click`) conflict with these policies, errors will occur.  
   - **Solution**: Ensure your script interacts only with valid elements, handles `null` values gracefully, and avoids any operation LinkedIn may consider unsafe. Example:
     ```javascript
     const connectButton = document.querySelector('button[aria-label*="Invite"][aria-label*="connect"]');
     if (connectButton) {
         connectButton.click();
         console.log('Connection sent!');
     } else {
         console.warn('Connect button not found. Skipping this iteration.');
     }
     ```

3. **Browser Extensions**:  
   Extensions like ad blockers or privacy tools might modify LinkedIn’s CSP or DOM structure, leading to unexpected errors.  
   - **Test**: Run the script in an incognito window (with extensions disabled).  

4. **LinkedIn Version or DOM Differences**:  
   LinkedIn often uses A/B testing, which can change the page layout or attributes slightly. Your script might fail if elements like buttons have different `aria-label` values.  
   - **Solution**: Add more robust element detection, such as `contains` or fallback selectors:
     ```javascript
     const connectButton = document.querySelector('button[aria-label*="Invite"][aria-label*="connect"], button[title="Connect"]');
     ```

5. **Browser-Specific Issues**:  
   Although we’re both using Chrome, differences in settings (e.g., CSP enforcement levels or experimental flags) could impact the script’s execution.  
   - **Test**: Ensure you’re running the latest Chrome version and that no experimental features are enabled.

---

I'm not sure why it's not working in your setup, but if you view the video, you can see it does, in fact, run an error-free in stock Chrome (fresh install). If you figure out the issue you're having please let me know. And I'm sorry I couldn't be of more help. 

https://github.com/user-attachments/assets/44bc6ed7-d31b-4c24-9a08-3f7fc3d26e3b

**Comment by NatsumeAoii** [comment]
I appreciate the time you took to troubleshoot and outline potential causes for the issue. I’ll continue testing on my end and update you if I find a fix. Let me know if there’s anything else I should try or consider.
